### PR TITLE
Move websites to void and nginx

### PR DESCRIPTION
**Pull request by m-wynn**
- [x] Create Nginx Role
- [x] Move doc_site to nginx
- [x] Move nut_site to nginx
- [x] Move jekyll to nginx
- [x] Move papercut_site to nginx
- [x] Move pasta_site to nginx
- [x] Move preseed_site to nginx
- [x] Move irc_site to nginx
- [x] ~~Move account_site to nginx~~
- [x] ~~Move ldap_restful to nginx~~

### CODE REVIEW

**Comment by m-wynn** [comment]
Waiting on voidlinux/void-packages#4150

**Comment by Vaelatern** [comment]
No longer waiting.

**Comment by m-wynn** [comment]
Everything else is waiting for krb5-tools or icinga.

**Comment by Vaelatern** [comment]
How are the krb5-tools coming along? I see `mit-krb5` in the repos, but don't even see a PR for the others.

**Comment by m-wynn** [comment]
I don't think we have any void dependencies for krb5-tools at this time.  We just haven't made our way to krb5-tools yet in the refactor.

**Pull request closed without merging**
